---
version: '3.3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=thunderstorm
      - DOCKER_INFLUXDB_INIT_ORG=my-weather-station
      - DOCKER_INFLUXDB_INIT_BUCKET=ecowitt

volumes:
    influxdb-storage:
